name: actions test

on:
  workflow_dispatch:
    inputs:
      keyword:
        required: true
        description: キーワード

jobs:
  testJob1:
    runs-on: ubuntu-latest

    steps:
      - name: check
        id: check
        if: github.event.inputs.keyword == 'test'
        run: echo key ok!
      - name: if bunki
        if: steps.check.conclusion == 'success' 
        run: echo Hello, world!
      - name: if bunki2
        if: steps.check.conclusion == 'skipped' 
        run: echo Hello, world!!!

  testJob2:
    runs-on: ubuntu-latest
    needs: testJob1
    steps:
      - name: relase1
        if: steps.check.conclusion == 'success' 
        run: echo check success
