name: actions test

on:
  workflow_dispatch:
    inputs:
      keyword:
        required: true
        description: キーワード
      branchCheck:
        description: 選択しているブランチは正しいですか？
        required: true
        type: boolean

jobs:
  testJob1:
    runs-on: ubuntu-latest

    steps:
      - name: check
        id: check
        if: github.event.inputs.keyword == 'test' && github.event.inputs.branchCheck
        run: echo key and check ok!
      - name: if bunki
        if: steps.check.conclusion == 'success' 
        run: echo Hello, world!
      - name: if bunki2
        if: steps.check.conclusion == 'skipped' 
        run: echo Hello, world!!!

  testJob2:
    needs: testJob1
    runs-on: ubuntu-latest
    steps:
      - name: check
        id: check
        if: github.event.inputs.keyword == 'test' && github.event.inputs.branchCheck
        run: |
          echo key and check ok!
          echo key and check ok!
          echo key and check ok!

      - name: relase1
        if: steps.check.conclusion == 'success' 
        run: echo check success

      - name: relase2
        if: steps.check.conclusion == 'skipped' 
        run: echo check skip
